# Encoding

In [3]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('homeprices.csv')
df

    sno       town  area    price
0     0    Chennai  2600  5500000
1     1    Chennai  3000  5650000
2     2    Chennai  3200  6100000
3     3    Chennai  3600  6800000
4     4   Banglore  2600  5850000
5     5   Banglore  2800  6150000
6     6   Banglore  3300  6500000
7     7   Banglore  3600  7100000
8     8  Hyderabad  2600  5750000
9     9  Hyderabad  2900  6000000
10   10  Hyderabad  3100  6200000
11   11  Hyderabad  3600  6950000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sno     12 non-null     int64
 1   town    12 non-null     object
 2   area    12 non-null     int64
 3   price   12 non-null     int64
dtypes: int64(3), object(1)
memory usage: 512.0+ bytes

In [6]:
df["town"].value_counts()

Chennai      4
Banglore     4
Hyderabad    4
Name: town, dtype: int64

# Nominal Encoding

In [9]:
#Convert nominal categorical into numerical

#Option1: Get_dummies() using pandas

In [11]:
df_dum=pd.get_dummies(df,drop_first=True)
df_dum

    sno  area    price  town_Chennai  town_Hyderabad
0     0  2600  5500000             1               0
1     1  3000  5650000             1               0
2     2  3200  6100000             1               0
3     3  3600  6800000             1               0
4     4  2600  5850000             0               0
5     5  2800  6150000             0               0
6     6  3300  6500000             0               0
7     7  3600  7100000             0               0
8     8  2600  5750000             0               1
9     9  2900  6000000             0               1
10   10  3100  6200000             0               1
11   11  3600  6950000             0               1

In [14]:
#EXPLANATION Part get_dummies()

In [15]:
dummies=pd.get_dummies(df.town)
dummies

    Banglore  Chennai  Hyderabad
0          0        1          0
1          0        1          0
2          0        1          0
3          0        1          0
4          1        0          0
5          1        0          0
6          1        0          0
7          1        0          0
8          0        0          1
9          0        0          1
10         0        0          1
11         0        0          1

In [16]:
df_dummies=pd.concat([df,dummies],axis='columns')
df_dummies

    sno       town  area    price  Banglore  Chennai  Hyderabad
0     0    Chennai  2600  5500000         0        1          0
1     1    Chennai  3000  5650000         0        1          0
2     2    Chennai  3200  6100000         0        1          0
3     3    Chennai  3600  6800000         0        1          0
4     4   Banglore  2600  5850000         1        0          0
5     5   Banglore  2800  6150000         1        0          0
6     6   Banglore  3300  6500000         1        0          0
7     7   Banglore  3600  7100000         1        0          0
8     8  Hyderabad  2600  5750000         0        0          1
9     9  Hyderabad  2900  6000000         0        0          1
10   10  Hyderabad  3100  6200000         0        0          1
11   11  Hyderabad  3600  6950000         0        0          1

In [17]:
df_dummies.drop('town',axis='columns',inplace=True)
df_dummies

    sno  area    price  Banglore  Chennai  Hyderabad
0     0  2600  5500000         0        1          0
1     1  3000  5650000         0        1          0
2     2  3200  6100000         0        1          0
3     3  3600  6800000         0        1          0
4     4  2600  5850000         1        0          0
5     5  2800  6150000         1        0          0
6     6  3300  6500000         1        0          0
7     7  3600  7100000         1        0          0
8     8  2600  5750000         0        0          1
9     9  2900  6000000         0        0          1
10   10  3100  6200000         0        0          1
11   11  3600  6950000         0        0          1

In [18]:
df_dummies.drop('Banglore',axis='columns',inplace=True)
df_dummies

    sno  area    price  Chennai  Hyderabad
0     0  2600  5500000        1          0
1     1  3000  5650000        1          0
2     2  3200  6100000        1          0
3     3  3600  6800000        1          0
4     4  2600  5850000        0          0
5     5  2800  6150000        0          0
6     6  3300  6500000        0          0
7     7  3600  7100000        0          0
8     8  2600  5750000        0          1
9     9  2900  6000000        0          1
10   10  3100  6200000        0          1
11   11  3600  6950000        0          1

In [20]:
#Option 2: OneHotEncoder using Sklearn

In [21]:
from sklearn.preprocessing import OneHotEncoder

enc=OneHotEncoder(drop='first')

In [24]:
enc_df=pd.DataFrame(enc.fit_transform(df[['town']]).toarray())
enc_df

      0    1
0   1.0  0.0
1   1.0  0.0
2   1.0  0.0
3   1.0  0.0
4   0.0  0.0
5   0.0  0.0
6   0.0  0.0
7   0.0  0.0
8   0.0  1.0
9   0.0  1.0
10  0.0  1.0
11  0.0  1.0

In [25]:
#Merge with main df
df_ohe=pd.concat([df,enc_df],axis='columns')
df_ohe

    sno       town  area    price    0    1
0     0    Chennai  2600  5500000  1.0  0.0
1     1    Chennai  3000  5650000  1.0  0.0
2     2    Chennai  3200  6100000  1.0  0.0
3     3    Chennai  3600  6800000  1.0  0.0
4     4   Banglore  2600  5850000  0.0  0.0
5     5   Banglore  2800  6150000  0.0  0.0
6     6   Banglore  3300  6500000  0.0  0.0
7     7   Banglore  3600  7100000  0.0  0.0
8     8  Hyderabad  2600  5750000  0.0  1.0
9     9  Hyderabad  2900  6000000  0.0  1.0
10   10  Hyderabad  3100  6200000  0.0  1.0
11   11  Hyderabad  3600  6950000  0.0  1.0

In [27]:
#Drop the original variable
df_ohe.drop('town',axis='columns',inplace=True)
df_ohe

    sno  area    price    0    1
0     0  2600  5500000  1.0  0.0
1     1  3000  5650000  1.0  0.0
2     2  3200  6100000  1.0  0.0
3     3  3600  6800000  1.0  0.0
4     4  2600  5850000  0.0  0.0
5     5  2800  6150000  0.0  0.0
6     6  3300  6500000  0.0  0.0
7     7  3600  7100000  0.0  0.0
8     8  2600  5750000  0.0  1.0
9     9  2900  6000000  0.0  1.0
10   10  3100  6200000  0.0  1.0
11   11  3600  6950000  0.0  1.0

# 2.ORDINAL to NUMERIC Encoding

In [31]:
#Label encoder using sklearn
df=pd.read_csv('homeprices.csv')

##Import from sklearn library
from sklearn.preprocessing import LabelEncoder

##call the function
le=LabelEncoder()

##fit_transform
df["town"]=le.fit_transform(df["town"])
df

    sno  town  area    price
0     0     1  2600  5500000
1     1     1  3000  5650000
2     2     1  3200  6100000
3     3     1  3600  6800000
4     4     0  2600  5850000
5     5     0  2800  6150000
6     6     0  3300  6500000
7     7     0  3600  7100000
8     8     2  2600  5750000
9     9     2  2900  6000000
10   10     2  3100  6200000
11   11     2  3600  6950000

In [32]:
#Not alphabetical order

In [36]:
#Ordinal encoder using sklearn
df=pd.read_csv('homeprices.csv')

##Import from sklearn library
from sklearn.preprocessing import OrdinalEncoder

##call the function
oe=OrdinalEncoder(categories=[['Chennai','Hyderabad','Banglore']])

##fit_transform
df["town"]=oe.fit_transform(df[["town"]])
df

    sno  town  area    price
0     0   0.0  2600  5500000
1     1   0.0  3000  5650000
2     2   0.0  3200  6100000
3     3   0.0  3600  6800000
4     4   2.0  2600  5850000
5     5   2.0  2800  6150000
6     6   2.0  3300  6500000
7     7   2.0  3600  7100000
8     8   1.0  2600  5750000
9     9   1.0  2900  6000000
10   10   1.0  3100  6200000
11   11   1.0  3600  6950000

# OPTION 3.PD.MAP

In [38]:
df=pd.read_csv('homeprices.csv')

df['town']=df['town'].map({'Banglore':2,'Hyderabad':1,'Chennai':0})
df

    sno  town  area    price
0     0     0  2600  5500000
1     1     0  3000  5650000
2     2     0  3200  6100000
3     3     0  3600  6800000
4     4     2  2600  5850000
5     5     2  2800  6150000
6     6     2  3300  6500000
7     7     2  3600  7100000
8     8     1  2600  5750000
9     9     1  2900  6000000
10   10     1  3100  6200000
11   11     1  3600  6950000