# One Hot Encoder (Nominal Encoding)

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [3]:
d

{'sales': [100000,
  222000,
  1000000,
  522000,
  111111,
  222222,
  1111111,
  20000,
  75000,
  90000,
  1000000,
  10000],
 'city': ['Tampa',
  'Tampa',
  'Orlando',
  'Jacksonville',
  'Miami',
  'Jacksonville',
  'Miami',
  'Miami',
  'Orlando',
  'Orlando',
  'Orlando',
  'Orlando'],
 'size': ['Small',
  'Medium',
  'Large',
  'Large',
  'Small',
  'Medium',
  'Large',
  'Small',
  'Medium',
  'Medium',
  'Medium',
  'Small']}

In [4]:
df = pd.DataFrame(data=d)
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [5]:
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False).set_output(transform="pandas")

In [6]:
ohetransform = ohe.fit_transform(df[['city']])

In [7]:
ohetransform

    city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                 0.0         0.0           0.0         1.0
1                 0.0         0.0           0.0         1.0
2                 0.0         0.0           1.0         0.0
3                 1.0         0.0           0.0         0.0
4                 0.0         1.0           0.0         0.0
5                 1.0         0.0           0.0         0.0
6                 0.0         1.0           0.0         0.0
7                 0.0         1.0           0.0         0.0
8                 0.0         0.0           1.0         0.0
9                 0.0         0.0           1.0         0.0
10                0.0         0.0           1.0         0.0
11                0.0         0.0           1.0         0.0

In [18]:
df = pd.concat([df,ohetransform],axis=1).drop(columns=["city"])

In [19]:
df

      sales  size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0    100000   0.0                0.0         0.0           0.0         1.0
1    222000   1.0                0.0         0.0           0.0         1.0
2   1000000   2.0                0.0         0.0           1.0         0.0
3    522000   2.0                1.0         0.0           0.0         0.0
4    111111   0.0                0.0         1.0           0.0         0.0
5    222222   1.0                1.0         0.0           0.0         0.0
6   1111111   2.0                0.0         1.0           0.0         0.0
7     20000   0.0                0.0         1.0           0.0         0.0
8     75000   1.0                0.0         0.0           1.0         0.0
9     90000   1.0                0.0         0.0           1.0         0.0
10  1000000   1.0                0.0         0.0           1.0         0.0
11    10000   0.0                0.0         0.0           1.0         0.0

# Orinal Encoder

In [10]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [11]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [12]:
df = pd.DataFrame(data=d)
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [13]:
df['size'].unique()

array(['Small', 'Medium', 'Large'], dtype=object)

In [14]:
sizes = ['Small', 'Medium', 'Large']

In [15]:
enc = OrdinalEncoder(categories = [sizes])
enc.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.]])

In [16]:
df['size'] = enc.fit_transform(df[['size']])

In [17]:
df

      sales          city  size
0    100000         Tampa   0.0
1    222000         Tampa   1.0
2   1000000       Orlando   2.0
3    522000  Jacksonville   2.0
4    111111         Miami   0.0
5    222222  Jacksonville   1.0
6   1111111         Miami   2.0
7     20000         Miami   0.0
8     75000       Orlando   1.0
9     90000       Orlando   1.0
10  1000000       Orlando   1.0
11    10000       Orlando   0.0