# Data Understanding

1. Import Pandas and Load Dataset

In [1]:
import pandas as pd

df = pd.read_csv("tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

2. Dataset Shape

In [3]:
df.shape

(244, 7)

3.Dataset Information

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

4. Identify Variable Types
The PDF’s final line contains a typo (tips instead of tip and mismatched quotes). 
Below is corrected executable code. Continuous: total_bill, tip. Discrete numerical: size (party size). 
Categorical: sex, smoker, day, time. 
The source grouped size with the other noncontinuous columns; here it is separated because it is a count.

In [5]:
continuous = ["total_bill", "tip"]
discrete = ["size"]
categorical = ["sex", "smoker", "day", "time"]

print("Continuous:", continuous)
print("Discrete:", discrete)
print("Categorical:", categorical)

Continuous: ['total_bill', 'tip']
Discrete: ['size']
Categorical: ['sex', 'smoker', 'day', 'time']

5. Descriptive Statistics (Additional EDA)

In [6]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [7]:
df.describe(include="all")

        total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [8]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [9]:
for column in categorical:
    print(f"\n{column}:")
    print(df[column].value_counts())

sex:
Male      157
Female     87
Name: sex, dtype: int64

smoker:
No     151
Yes     93
Name: smoker, dtype: int64

day:
Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

time:
Dinner    176
Lunch      68
Name: time, dtype: int64